---
# tasks file for pycharm
- name: Instalar PyCharm usando Snap
  tags: [ snap, dev, python ]
  block:
      - name: Asegurarse de que Snap está instalado
        ansible.builtin.apt:
          name: snapd
          state: present

      - name: Instalar PyCharm
        community.general.snap:
          name: pycharm-community
          classic: true
