---
# tasks file for guiapps
- name: Instalar aplicaciones de interfaz gráfica
  tags: [ apt, gui ]
  ansible.builtin.apt:
    name: "{{ guiapps_packages }}"
    update_cache: true
    state: present
