---
- name: Descargar WordPress
  tags: [ wordpress, install ]
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  tags: [ wordpress, install ]
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copiar archivos de WordPress al directorio de instalación
  tags: [ wordpress, install, dirs ]
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes
