---
# tasks file for roles/code
- name: Instalar "{{ pkg_name }}" desde su repositorio
  tags: [ apt, repo, dev, gui, code ]
  block:
    - name: Download Microsoft GPG key
      ansible.builtin.get_url:
        url: "{{ gpg_key_url }}"
        dest: /etc/apt/trusted.gpg.d//{{key}}.asc

    - name: Convert Microsoft GPG key to binary format
      ansible.builtin.shell: gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/{{ key }}.gpg /etc/apt/trusted.gpg.d/{{ key }}.asc

    - name: Add Microsoft repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/vscode.list
        content: "{{ repo_url }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Visual Studio Code
      ansible.builtin.apt:
        name: "{{ repo }}"
        state: present