---
# tasks file for codec
- name: Instalar codecs
  tags: [ apt, codec ]
  ansible.builtin.apt:
    name: "{{ codec_packages + vaapi_packages + player_packages }}"
    update_cache: true
    state: present
